### PR TITLE
rama-27 - first open source contribution

### PR DESCRIPTION
**Pull request by rama-27**

### CODE REVIEW

**Comment by rama-27** [comment]
my first open source contribution :)

**Review by raspberri05 — CHANGES_REQUESTED** [review]
HI, thank you for your contribution. I noticed that your removed the current name in the contributors list and added your own. What you should do is make an entry on the next line that has your information, rather than removing the current information. You can make changes in your fork, and it should automatically update in this PR.

**Comment by rama-27** [comment]
sorry , i fixed it now . Thanks for reviewing :)

**Review by raspberri05 — APPROVED** [review]
Hi. thanks for your contribution! Everything looks good, so I'll go ahead and get this merged shortly. I also hope that you consider starring this repository so that it can reach more developers looking to get into open-source

**Pull request merged**
